apiVersion: v2
name: fortsa
description: A Helm chart to distribute fortsa
type: application
version: v0.5.1-34-gcf092cc
appVersion: "v0.5.1-34-gcf092cc"
keywords:
  - kubernetes
  - operator
annotations:
  kubebuilder.io/generated-by: kubebuilder
