apiVersion: v2
name: fortsa
description: A Helm chart to distribute the project fortsa
type: application
version: v0.5.1-33-g5e7dfc1
appVersion: "v0.5.1-33-g5e7dfc1"
icon: "https://example.com/icon.png"
